version: "3"
services:
     web:
      build: .
      ports:
       - "80:80"
     db:
       image: mysql
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: redhat
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wp_user
         MYSQL_PASSWORD: password

